<div class="modal-wrapper" id="popup-legales">
    <div class="popup-contenedor-legales">
       <h6>Reservas Legales</h6>
       <hr>
       <p>La información y los materiales contenidos en este sitio se proporcionan, tal como son. Cofco Intl. no se asegura ni garantiza que los mismos sean exactos, suficientes o completos y niega expresamente toda responsabilidad que se le pudiera imputar por los errores y/u omisiones en la información y materiales contenidos en este sitio y/o por cualquier uso y acto realizado como consecuencia o en confianza de la información y los materiales publicados en el sitio web. Ningún tipo de garantía, ni expresa ni tacita, es otorgada por la información y los materiales publicados en este sitio web. Cofco Intl. y ciertos subsidiarios de Cofco compran o venden commodities por su propia cuenta, basándose en la información contenida en este sitio web y en cualquier momento pueden poseer o tener contratos que lo obliguen a entregar tales commodities o a hacer pagos con respecto a la información relativa a dichos commodities, y/o dándoles derechos a recibir tales materiales o a recibir pagos con respecto a la información relativa a ellos. Cofco y/o sus subsidiarios y afiliados podrán tomar posiciones que sean diferentes u opuestas a las posiciones tratadas en el presente. La información contenida en este sitio web es proporcionada en forma gratuita solamente a fines informativos y no con la intención de ser tomada como oferta, solicitud o recomendación con respecto a cualquier transacción que involucre a cualquier commodity. Cofco Intl. no es asesor comercial de commodities ni comisionista de mercados a futuro. Cofco Intl. proporciona la información contenida en este sitio web solamente en lo que incide a su negocio en el mercado de capitales. Cualquier información con respecto al intercambio y negocio de contratos a futuro y de opciones se proporciona solamente como una conveniencia a los usuarios de este sitio del web y no genera ningún tipo de obligación contractual o extracontractual hacia Cofco Intl., bajo ningún concepto.</p>
       <hr>
       <a class="popup-cerrar" href="#">X</a>
    </div>
 </div>
